[package]
name = "ewq"
description = "Small math library"
license = "MIT"
repository = "https://github.com/sy1ntexx/ewq"
readme = "README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
